name: fretwise
description: "Fretwise — Guitar Learning App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  provider: ^6.1.2
  audioplayers: ^6.1.0
  pitch_detector_dart: ^0.0.7
  mic_stream: ^0.7.2
  
  # --- 新增的 Firebase 與 影片套件 ---
  firebase_core: ^2.32.0
  cloud_firestore: ^4.17.5
  firebase_auth: ^4.19.6
  cloud_functions: ^4.7.5
  youtube_player_flutter: ^8.1.2

flutter:
  uses-material-design: true
